- name: Add apt repository for nginx
  become: yes
  apt_repository:
    repo: deb http://nginx.org/packages/mainline/ubuntu/ xenial nginx
    state: present

- name: Add nginx signing key
  become: yes
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Install nginx
  become: yes
  apt:
    name: nginx
    update_cache: yes
    state: latest

- name: Set new nginx.conf
  become: yes
  copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Set new nginx default site
  become: yes
  copy:
    src: ../files/server.conf
    dest: /etc/nginx/conf.d/default
